#!/usr/bin/env python3
"""Generate catalog metadata from executable Razor examples and the public source API."""
from pathlib import Path
import json, re, sys, html
root = Path(__file__).resolve().parent.parent
project = root / 'samples/Sufficit.Blazor.UI.Demos'
families = {'Actions':'Ações','Forms':'Formulários','Layout':'Layout','Navigation':'Navegação','DataDisplay':'Dados','Feedback':'Feedback','Overlays':'Overlays','Themes':'Temas'}
def standalone(example):
    code = (project/'DemoBase.cs').read_text().split('public abstract class DemoBase : ComponentBase', 1)[1].strip()[1:-1]
    members = {}
    starts = list(re.finditer(r'^    (?:\[Inject\] )?protected (?:async )?[^\n]+', code, re.M))
    for i, match in enumerate(starts):
        member = code[match.start():starts[i+1].start() if i+1<len(starts) else len(code)].rstrip()
        signature = match.group(0)
        names = re.findall(r'\b(\w+)\s*(?:\{|\()', signature)
        if names: members[names[0]] = member
    markup = example.read_text().replace('@inherits DemoBase\n', '').strip()
    required = {name for name in members if re.search(r'\b'+name+r'\b', markup)}
    while True:
        used = '\n'.join(members[name] for name in required)
        expanded = required | {name for name in members if re.search(r'\b'+name+r'\b', used)}
        if expanded == required: break
        required = expanded
    selected = '\n'.join(member for name,member in members.items() if name in required)
    return '@using Sufficit.Blazor.UI.Components\n@using Sufficit.Blazor.UI.Services\n\n'+markup+('\n\n@code {\n'+selected+'\n}\n' if selected else '\n')

items = []
for component in sorted((root/'src').rglob('*.razor')):
    if 'obj' in component.parts or 'bin' in component.parts or component.stem == '_Imports': continue
    name = component.stem
    example = project/'Examples'/(name+'Example.razor')
    if not example.exists(): raise SystemExit(f'Missing executable example: {name}')
    source = component.read_text()
    if component.with_suffix('.razor.cs').exists(): source += '\n'+component.with_suffix('.razor.cs').read_text()
    parameters = []
    for match in re.finditer(r'((?:\[[^\]]*\]\s*)+)public\s+([^\n]+?)\s+(\w+)\s*\{\s*get;\s*set;\s*\}(?:\s*=\s*([^;\n]+);)?', source):
        flags, typ, param, default = match.groups()
        if not re.search(r"\bParameter\b", flags): continue
        preceding = source[:match.start()]
        summary = re.search(r'/// <summary>(.*?)</summary>\s*$', preceding, re.S)
        description = ''
        if summary:
            # Take the nearest summary; do not absorb earlier members.
            raw = summary.group(1).rsplit('/// <summary>', 1)[-1]
            raw = re.sub(r'<see\s+cref="([^"]+)"\s*/>', r'\1', raw)
            description = html.unescape(re.sub(r'<[^>]+>', '', raw).replace('///', '').strip())
            description = re.sub(r'\s+', ' ', description)
        parameters.append({'description': description, 'name':param, 'type':typ, 'default':default or 'Padrão do tipo', 'required':'EditorRequired' in flags, 'deprecated':'Obsolete' in flags})
    items.append({'name':name,'family':families[component.parent.name], 'source':standalone(example), 'parameters':parameters})
jsontext=json.dumps(items,ensure_ascii=False,indent=2)+'\n'
registry='''// Generated by scripts/generate-catalog.py. Do not edit.
namespace Sufficit.Blazor.UI.Demos;
public static partial class DemoCatalog
{
    public static Type ExampleType(string name) => name switch
    {
'''+''.join(f'        "{x["name"]}" => typeof(Examples.{x["name"]}Example),\n' for x in items)+'''        _ => throw new ArgumentOutOfRangeException(nameof(name)),
    };
}
'''
for file, content in [(project/'catalog.json',jsontext),(project/'DemoCatalog.Generated.cs',registry)]:
    if '--check' in sys.argv:
        if not file.exists() or file.read_text()!=content: raise SystemExit(f'Stale catalog file: {file}')
    else:file.write_text(content)
print(f'Catalog: {len(items)} components with executable examples and public parameters.')
